# permissions for end users to view poddiskinspectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: poddiskinspector-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pvc-autoscaler-operator
    app.kubernetes.io/part-of: pvc-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiskinspector-viewer-role
rules:
- apiGroups:
  - autoscaler.allthatjazzleo
  resources:
  - poddiskinspectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaler.allthatjazzleo
  resources:
  - poddiskinspectors/status
  verbs:
  - get
