---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - pvc-autoscaler-operator-mutating-webhook-configuration
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - autoscaler.allthatjazzleo
  resources:
  - poddiskinspectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaler.allthatjazzleo
  resources:
  - poddiskinspectors/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaler.allthatjazzleo
  resources:
  - poddiskinspectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resourceNames:
  - pvc-autoscaler-operator-webhook-server-cert
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
