apiVersion: autoscaler.allthatjazzleo/v1alpha1
kind: PodDiskInspector
metadata:
  labels:
    app.kubernetes.io/name: poddiskinspector
    app.kubernetes.io/instance: poddiskinspector-sample
    app.kubernetes.io/part-of: pvc-autoscaler-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pvc-autoscaler-operator
  name: poddiskinspector-sample
spec:
  # disk health check image
  sidecarImage: "allthatjazzleo/pvc-autoscaler-operator:v0.0.2"
  pvcScaling:
    usedSpacePercentage: 80
    increaseQuantity: 20%
    cooldown: 6h
    maxSize: 16Ti
